DROP TABLE IF EXISTS url;

CREATE TABLE url (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    short_code TEXT UNIQUE NOT NULL,
    original_url TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    click_count INTEGER NOT NULL DEFAULT 0
);

CREATE TRIGGER update_timestamp
AFTER UPDATE ON url
FOR EACH ROW
BEGIN
    UPDATE url
    SET updated_at = CURRENT_TIMESTAMP
    WHERE id = OLD.id;
END;